name: Build Production Tag
on: 
  push:
    tags:
      - 'v*.*.*'
jobs:
  # build-registry:
  #   runs-on: ubuntu-latest
  #   env:
  #     PROJECT_ID: reyid-310002
  #     PROJECT_NUMBER: 525431198450
  #     SVC_NAME: rey-default-svc-ts
  #     SVC_ACC_NAME: service-account
  #     SVC_ACC_KEY: ${{ secrets.GCLOUD_SERVICE_KEY_PRODUCTION }}
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Declare variable
  #       id: vars
  #       shell: bash
  #       run: |
  #         echo "::set-output name=tag::${GITHUB_REF#refs/*/}"

  #     - uses: google-github-actions/setup-gcloud@v0
  #       with:
  #         project_id: ${{ env.PROJECT_ID }}
  #         service_account_key: ${{ env.SVC_ACC_KEY }}
  #         export_default_credentials: true

  #     - id: secrets
  #       uses: google-github-actions/get-secretmanager-secrets@main
  #       with:
  #         secrets: |-
  #           token:${{ env.PROJECT_NUMBER }}/${{ env.SVC_NAME }}
  #           svc_acc:${{ env.PROJECT_NUMBER }}/${{ env.SVC_ACC_NAME }}

  #     - name: Create env file
  #       env:
  #        ENV_FILE: ${{ steps.secrets.outputs.token }}
  #       run: echo $ENV_FILE | tr " " "\n" > .env

  #     - name: Create service account file
  #       env:
  #        SVC_ACC_FILE: ${{ steps.secrets.outputs.svc_acc }}
  #       run: echo $SVC_ACC_FILE > svc_account.json

  #     - name: Build and Push
  #       uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
  #       with:
  #         gcloud_service_key: ${{ env.SVC_ACC_KEY }}
  #         registry: asia.gcr.io
  #         project_id: ${{ env.PROJECT_ID }}
  #         image_name: ${{ env.SVC_NAME }}
  #         image_tag: ${{ steps.vars.outputs.tag }}
  #         dockerfile: ./Dockerfile

  publish-release:
    name: publish-release
    # needs: build-registry
    runs-on: ubuntu-latest
    steps:

    - name: create release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.PAT }}"
        prerelease: false
