# name: Build Production Tag
# on: 
#   push:
#     tags:
#       - 'v*.*.*'
# jobs:
#   build-and-push-gcr:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set output
#         id: vars
#         run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
#       - name: Check output
#         env:
#           RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
#         run: |
#           echo $RELEASE_VERSION
#       - uses: google-github-actions/setup-gcloud@master
#         env:
#           PROJECT_ID: reyinfra
#         with:
#           project_id: ${{ env.PROJECT_ID }}
#           service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
#           export_default_credentials: true
#       - id: secrets
#         uses: google-github-actions/get-secretmanager-secrets@main
#         with:
#           secrets: |-
#             token:projects/481152137866/secrets/rey-purchase
#             svc_acc:projects/481152137866/secrets/service-account
#       - name: Create env file
#         env:
#          ENV_FILE: ${{ steps.secrets.outputs.token }}
#         run: echo $ENV_FILE | tr " " "\n" > .env
#       - name: Create service account file
#         env:
#          SVC_ACC: ${{ steps.secrets.outputs.svc_acc }}
#         run: echo $SVC_ACC > svc_account.json
#       - name: Build and Push
#         uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
#         env:
#           TAG: ${{ steps.get_tag.output.GIT_TAG_NAME }}
#         with:
#           gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
#           registry: asia.gcr.io
#           project_id: reyinfra
#           image_name: rey-purchase
#           image_tag: ${{ steps.vars.outputs.tag }}
#           dockerfile: ./Dockerfile
