# name: Run Staging Migration
# on: 
#   workflow_dispatch:
#     inputs:
#       command:
#         description: sequelize cli command (db:migrate / db:migrate:undo)
#         required: true
# jobs:
#   migration:
#     runs-on: ubuntu-latest
#     env:
#       DB_CONNECTION_STRING: postgresql://${{ secrets.DB_USER_STAGING }}:${{ secrets.DB_PASS_STAGING }}@127.0.0.1:5432/rey-purchase
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         persist-credentials: false
#     - uses: mattes/gce-cloudsql-proxy-action@v1
#       with:
#         creds: ${{ secrets.GCLOUD_SERVICE_KEY_DECODED_STAGING }}
#         instance: ${{ secrets.DB_INSTANCE_STAGING }}
#     - name: Use Node.js 12
#       uses: actions/setup-node@v2
#       with:
#         node-version: '12'
#     - run: npm install dotenv sequelize pg
#     - run: npx sequelize-cli ${{ github.event.inputs.command }}
