name: Create Release Tag
on:
  push:
    branches:
      - 'master'

jobs:
  release-tag:
    # if: ${GITHUB_REF##*/} == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: create tag
        uses: rickstaa/action-create-tag@v1.2.2
        with:
          tag: ${{ steps.package-version.outputs.current-version }}