name: Create Release Tag
on:
  push:
    branches:
      - 'release'

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: Create new tag
        uses: rickstaa/action-create-tag@v1.2.2
        with:
          tag: "v${{ steps.package-version.outputs.current-version }}"

      - name: Merge release to master
        uses: devmasx/merge-branch@v1.4.0
        with:
          label_name: 'merge release back to master'
          type: now
          target_branch: master
          github_token: ${{ secrets.PAT }}